- .travis.yml
Play Services is not needed for this project, so not pulling down this dependency will speed up the Travis builds.
Not sure why it is modifying that last line, just an artifact of using the GitHub editor I suppose 😄
> Remove play services lib from Travis to speed up builds

- .travis.yml
Sorry, this should have been in https://github.com/airbnb/lottie-android/pull/22 but I missed them somehow. Neither of these are needed for the Travis build, so it should speed up the time taken on builds a bit.
> Remove support lib and play services from Travis

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Currently LottieAnimationView can't be rendered in edit mode which is unfortunate because it prevents the layout from being shown in the layout preview without error.
This pull request changes the init() method of the LottieAnimationView so the animation is only set if the view is not in edit mode (e.g. layout preview).
> Bugfix - Render LottieAnimationView in edit mode

- lottie/src/main/java/com/airbnb/lottie/layers/AnimatableLayer.java
- lottie/src/main/java/com/airbnb/lottie/layers/LottieDrawable.java
Previously, LottieDrawable would invalidate itself with whatever layer changed. This would fail verification in [View](https://github.com/android/platform_frameworks_base/blob/master/core/java/android/view/View.java#L17951).
This bubbles up invalidate calls so that the drawable will invalidate itself with `LottieDrawable`.
Fixes #37
> Invalidate LottieDrawable with itself so that it can be verified

- lottie/src/main/java/com/airbnb/lottie/AnimatableColorValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableFloatValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableIntegerValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatablePathValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatablePointValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableScaleValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableShapeValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableSplitDimensionPathValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableTransform.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableValue.java
- lottie/src/main/java/com/airbnb/lottie/BaseAnimatableValue.java
- lottie/src/main/java/com/airbnb/lottie/CircleShape.java
- lottie/src/main/java/com/airbnb/lottie/CompositionLayer.java
- lottie/src/main/java/com/airbnb/lottie/JsonUtils.java
- lottie/src/main/java/com/airbnb/lottie/Keyframe.java
- lottie/src/main/java/com/airbnb/lottie/L.java
- lottie/src/main/java/com/airbnb/lottie/Layer.java
- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/Mask.java
- lottie/src/main/java/com/airbnb/lottie/PathKeyframe.java
- lottie/src/main/java/com/airbnb/lottie/PolystarShape.java
- lottie/src/main/java/com/airbnb/lottie/RectangleShape.java
- lottie/src/main/java/com/airbnb/lottie/ShapeFill.java
- lottie/src/main/java/com/airbnb/lottie/ShapeGroup.java
- lottie/src/main/java/com/airbnb/lottie/ShapePath.java
- lottie/src/main/java/com/airbnb/lottie/ShapeStroke.java
- lottie/src/main/java/com/airbnb/lottie/ShapeTrimPath.java
* The parsing code is now cleaner.
* There is a slight performance improvement using opt* instead of get*. I did some tests and didn't see a significantly measurable improvement but for large files or on certain devices, it may make a difference.
Fixes #123 
#3
> Converted all json to use opt* instead of get*

- LottieSample/src/androidTest/java/com/airbnb/lottie/LottieTest.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableTransform.java
- lottie/src/main/java/com/airbnb/lottie/CircleShape.java
- lottie/src/main/java/com/airbnb/lottie/ImageAsset.java
- lottie/src/main/java/com/airbnb/lottie/ImageAssetBitmapManager.java
- lottie/src/main/java/com/airbnb/lottie/Keyframe.java
- lottie/src/main/java/com/airbnb/lottie/Layer.java
- lottie/src/main/java/com/airbnb/lottie/LayerView.java
- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/Mask.java
- lottie/src/main/java/com/airbnb/lottie/PathKeyframe.java
- lottie/src/main/java/com/airbnb/lottie/PolystarShape.java
- lottie/src/main/java/com/airbnb/lottie/RectangleShape.java
- lottie/src/main/java/com/airbnb/lottie/ShapeFill.java
- lottie/src/main/java/com/airbnb/lottie/ShapeGroup.java
- lottie/src/main/java/com/airbnb/lottie/ShapePath.java
- lottie/src/main/java/com/airbnb/lottie/ShapeStroke.java
- lottie/src/main/java/com/airbnb/lottie/ShapeTrimPath.java
Another change for #3
Pretty mechanical and straightforward change. Extracted a bunch of constructors into more static inner factory classes with a `newInstance` method by convention.
Later on we can pull out all these factories into a separate module that provides the default json parsing implementation.
> Extract more factory classes

- README.md
- lottie/src/main/java/com/airbnb/lottie/Cancellable.java
You can do this ...
```
LottieComposition.Factory.fromJson(getResources(),
new JSONObject(), new OnCompositionLoadedListener() {
@Override
public void onCompositionLoaded(LottieComposition composition) {
...
}
});
```
But you cannot do this ...
```
Cancellable compositionCancellable = LottieComposition.Factory.fromJson(getResources(),
new JSONObject(), new OnCompositionLoadedListener() {
@Override
public void onCompositionLoaded(LottieComposition composition) {
...
}
});
compositionCancellable.cancel();
```
Also on the README.md the examples show the old style ```LottieComposition.fromJson``` as opposed to ```LottieComposition.Factory.fromJson```
> Cancellable is returned by public functions, but isn't accessible

- lottie/src/main/java/com/airbnb/lottie/AnimatableColorValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableFloatValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableIntegerValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatablePathValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatablePointValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableScaleValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableShapeValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableSplitDimensionPathValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableTransform.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableValue.java
- lottie/src/main/java/com/airbnb/lottie/AnimatableValueParser.java
- lottie/src/main/java/com/airbnb/lottie/BaseAnimatableValue.java
- lottie/src/main/java/com/airbnb/lottie/CircleShape.java
- lottie/src/main/java/com/airbnb/lottie/ColorFactory.java
- lottie/src/main/java/com/airbnb/lottie/Keyframe.java
- lottie/src/main/java/com/airbnb/lottie/Mask.java
- lottie/src/main/java/com/airbnb/lottie/PathKeyframe.java
- lottie/src/main/java/com/airbnb/lottie/PointFFactory.java
- lottie/src/main/java/com/airbnb/lottie/PolystarShape.java
- lottie/src/main/java/com/airbnb/lottie/RectangleShape.java
- lottie/src/main/java/com/airbnb/lottie/ScaleXY.java
- lottie/src/main/java/com/airbnb/lottie/ShapeData.java
- lottie/src/main/java/com/airbnb/lottie/ShapeFill.java
- lottie/src/main/java/com/airbnb/lottie/ShapePath.java
- lottie/src/main/java/com/airbnb/lottie/ShapeStroke.java
- lottie/src/main/java/com/airbnb/lottie/ShapeTrimPath.java
In this pass I've converted `BaseAnimatableValue` and its subclasses.
Created a `AnimatableValueParser` with the common logic to all subclasses.
This change caused a "chicken and egg" problem where the `AnimatableValueParser` calls into `Keyframe.Factory.parseKeyframes`, which needs the respective instance of `BaseAnimatableValue`. This caused a circular dependency issue. I've resolved by moving `AnimatableValue#valueFromObject()` into a separate interface called `AnimatableValue.Factory` which contains only that method.
I think almost all the relevant classes have been refactored by now.
Part of #3
> Extract factories for Animatable classes

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
@gpeal 
Addresses https://github.com/airbnb/lottie-android/issues/149
Any ideas on the best way to test this? I looked at the test robot and it only sets a composition once, so that wouldn't catch any issues with a second composition not working correctly. I couldn't think of good way to test this without creating a new test approach. Seems like a robot method that sets the same composition twice, and then different compositions, on the same view would work.
> Only update lottie drawable if composition changes

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Update for https://github.com/airbnb/lottie-android/issues/159 — `invalidateDrawable(Drawable)` should call `super` for non-Lottie resources.
> Fix invalidateDrawable method behavior for non-Lottie images

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
* Databinding, when used in tandem with an initial static image can cause the LottieDrawable instance to be null/not intialized.
Issue exists on PIxel XL 7.1.1 and 7.1.2 using latest stable source (1.5.3).
> Assert LottieDrawable when recycling bitmaps

- README.md
(suggestion for us lazy copy pasters) if animation file specified through xml it starts playing automatically, thus the true equivalent to setting this in java, would require `playAnimation`
> chore: update README to indicate playAnimation

- lottie/src/main/java/com/airbnb/lottie/CompositionLayer.java
This also won't draw a precomp if its clip rect is empty which should have some performance improvements in some cases.
#281
> Clip precomps to their bounds

- lottie/src/main/java/com/airbnb/lottie/ImageAssetBitmapManager.java
If a null is returned in `ImageAssetDelegate.fetchBitmap()`,` recycleBitmaps()`  method Throws a NullPointerException
> fix NullPointerException

- lottie/build.gradle
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java
This is the second major LottieValueAnimator overhaul. The first one wound up being overly complex and didn't work great. This cleans up the logic and adds a bunch of unit tests.
This is a breaking change because it removes some confusing APIs such as `resumeReverseAnimation`. You now just set a negative speed and call `resumeAnimation`
Fixes #492 
Fixes #483
> Significant animator overhaul

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
This pull request updates `LottieDrawable` to implement the `Animatable` interface. See #579.
The implementation behaves the same as it does for `AnimatedVectorDrawable`s: https://github.com/aosp-mirror/platform_frameworks_base/blob/oreo-mr1-release/graphics/java/android/graphics/drawable/AnimatedVectorDrawable.java#L893-L945
TLDR:
* `start()` calls `playAnimation()`
* `stop()` calls `animator.end()`
* `isRunning()` calls `isAnimating()`
> make lottie drawable implement animatable

- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/parser/LottieCompositionParser.java
- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
In order for Utils.isAtLeastVersion to work, the init method needs to be called before it, but it was not. This removes the unnecessary variables that were being stored without need. Since they were restricted to the library and only being used there, I removed them.
> Fix min bodymoving version check.

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Before this, if a composition was loaded async after an existing composition was set, calls to LottieAnimationView would still be called on the old animation because it was still set as the active animation. This clears the existing one while a new one is being loaded so that new calls get added to the lazy composition tasks queue.
@phoca this will fix your issue in #287
> Clear the composition when a new one is set

- lottie/src/main/java/com/airbnb/lottie/utils/BaseLottieAnimator.java
This change will prevent `ConcurrentModificationException`.
> Use thread-safe set for listeners. Closes #639

- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
Fixes #656 
`getMinFrame()` will return `composition.getStartFrame()` if minFrame has not been set. This mimics how `getMaxFrame()` returns `composition.getEndFrame()` if maxFrame has not been set.
> Fix LottieValueAnimator when LottieComposition has a non-zero startFrame

- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/main/res/values/ids.xml
As of 2.5.0, Lottie would try and match the framerate specified in After Effects. This ends up just making things look janky most of the time. This reverts that to the old behavior of rendering every frame.
Fixes #647
> Render every frame instead of matching AE fps

- LottieSample/src/androidTest/java/com/airbnb/lottie/LottieSnapshotProvider.java
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Previously, if you set an animation, switched to a drawable, and switched back to *the same* animation, LottieDrawable would report that the composition was the same and it would not update the drawable on LottieAnimationView.
Thanks for catching this @sin3hz
Fixes #648
> Update the drawable when the composition is reset to the same one

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
This is needed in order to make more sophisticated and efficient update for the react-native plugin for Android.
> DEFAULT_CACHE_STRATEGY exposed.

- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
Composition can be loaded after we have set a custom `minFrame` and/or `maxFrame`.
The composition will override custom values.
> Fix race condition with min/max frame

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java
This should handle both cases where:
1) You set a min/max frame while the composition is still loading #694 
2) You change the composition to one with a different length #750
Added a bunch of tests to confirm as well
> Reset min/max frames unless no composition is set

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java
Fixes #763
Added test for bug in LottieDrawableTest. Fixed tests for `setMinProgress` and `setMaxProgress` since the tests would pass if the with the broken method of calculating frame.
For example, given progress of 0.5, endFrame of 200, and startFrame of 0
`0.5 * (200 - 0) == 0 + (0.5 * (200 - 0))`
whereas given progress of 0.5, endFrame of 200, and startFrame of 20
`0.5 * (200 - 20) = 90`
`20 + (0.5 * (200 - 20) = 110`
> Use lerp calculation to get the min and max frame.

- lottie/src/main/java/com/airbnb/lottie/parser/LayerParser.java
- lottie/src/main/java/com/airbnb/lottie/parser/LottieCompositionParser.java
- lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java
The end frame in the JSON represents the first instant after the animation ends. For example, if the end frame is 60, it should be visible until 59.999999... This fixes the logic for how end frames are calculated.
> Fixed end frame calculation

- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java
**This patch fixes the performance issue.**
I've seen the cases where the previous version of the code was re-adding callbacks to the choreographer in case of cancelation/pause. Now it is designed to make it impossible. It looks like there is a copy of the callbacks stored somewhere in the stack. I've been able to reproduce the problem on Android 6.0 and 7.0.
This issue caused application performance degradation and battery drain in the background for us.
> Fixed danglign choreographer callback.

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
**Reproduce code:**
```
val view = findViewById<LottieAnimationView>(R.id.lottie_view)
lottieView.setAnimation("HamburgerArrow.json")
lottieView.setMinFrame(111)
lottieView.setMaxFrame(141)
lottieView.playAnimation()
```
**Expected:**
The animation stopped in hamburger.
**Actual:**
It plays the whole animation from hamburger to arrow then from arrow to hamburger.
> Fix frame limit not apply to loaded composition

- lottie/src/main/java/com/airbnb/lottie/model/layer/ImageLayer.java
Use a recycled bitmap may produce a crash
> Fix ImageLayer.java may use a recycled bitmap 

- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
`public void setMinAndMaxFrames(int minFrame, int maxFrame)` started to behave strange when I updated. So I debug it. I found something very (very) strange.
If `composition` is `null`, `compositionMinFrame` will be set to `Float.MIN_VALUE`.  
And if I pass to the function `minFrame = 0` then... (attach your belt...)
`MiscUtils.clamp(minFrame, compositionMinFrame, compositionMaxFrame)`
=> `MiscUtils.clamp(0, Float.MIN_VALUE, Float.MAX_VALUE)`
**give `1.4E-45` (ouch!)**
... I don't know exactly why but `(Float.MIN_VALUE >= 0) == true`!
It's probably because the float are cast to `int`.
Anyway, elsewhere we use `Integer.MIN_VALUE` and `Integer.MAX_VALUE` for `this.minFrame` and `this.maxFrame` 👍
> Fix setMinAndMaxFrames

- lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java
* clipRect is deprecated with a Region.Op other than Region.Op.INTERSECT and Region.Op.DIFFERENCE
Signed-off-by: Brandon McAnsh <bmcansh@powerley.com>
> CompositionLayer: Handle invalid Region.Op on Android Pie

- lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java
Reproduce step:
1. Open a Lottie animation with external image reference, for example: `assets/Tests/WeAccept.json`
2. Close animation by press back button
3. Reopen same Lottie animation, the animation doesn't display.
For more details of this problem, please reference: https://github.com/cdotchen/lottie-android/pull/1
> Fix recycle asset bitmap improperly

- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/LottieFontViewGroup.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/java/com/airbnb/lottie/LottieTask.java
- lottie/src/main/java/com/airbnb/lottie/model/LottieCompositionCache.java
- lottie/src/main/res/values/attrs.xml
- lottie/src/test/java/com/airbnb/lottie/model/LottieCompositionCacheTest.java
This cleans up a number of things related to the LottieCompositionFactory.
It:
* Handled task caching at the LottieCompositionFactory level so it is guaranteed to work everywhere. The existing architecture left several instances where compositions would not be cached.
* Simplified the way tasks are handled in `LottieAnimationView`
* Fixes #958 in which different cache keys are used for rawRes animations
* Removed deprecated factory APIs
> LottieCompositionFactory and Caching Cleanup

- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java
I tracked this back as the root cause of this error:
```
Fatal Exception: java.lang.IllegalStateException: Frame must be [117,000000,19,000000]. It is 19,000000
at com.airbnb.lottie.utils.LottieValueAnimator.verifyFrame(LottieValueAnimator.java:270)
at com.airbnb.lottie.utils.LottieValueAnimator.doFrame(LottieValueAnimator.java:114)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
...
```
> Don't allow minFrame > maxFrame in LottieValueAnimator

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java
Added a call to the LRU Memory cache for lottie network requests.
I've also removed the asyncFetch calls from the NetworkFetcher since the url lottie composition creates an Async task from the LRU cache call
> Added memory cache layer for async network requests

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ColorKeyframeAnimation.java
Interpolating out of [0, 1] for colors can cause undesired effects and animations into totally different colors.
Fixes #970
> Prevent interpolating before the start color/after the end color

- lottie/src/main/java/com/airbnb/lottie/ImageAssetDelegate.java
According to the example in https://airbnb.io/lottie/android/images.html#providing-your-own-images, fetchBitmap() can return null and Lottie will keep asking until a non-null Bitmap is returned.
> Annotate fetchBitmap as @Nullable

- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/parser/GradientStrokeParser.java
- lottie/src/main/java/com/airbnb/lottie/parser/ShapeStrokeParser.java
Dash path effects are the only feature that Lottie uses that isn't supported on all api levels. We should be able to safely detect this [one case for API < 28](https://developer.android.com/guide/topics/graphics/hardware-accel#unsupported) and turn on hardware acceleration otherwise.
This removes the existing APIs since they no longer have a function.
> [Breaking Change] Automatic hardware acceleration detection

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
Some animations like `im_thirsty.json` broke with the old method and this one should be more performant anyways since it doesn't have to calculate the hashCode().
Fixes #1059
> Skip listeners based on keyframes

- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/RenderMode.java
- lottie/src/main/java/com/airbnb/lottie/parser/LayerParser.java
- lottie/src/main/res/values/attrs.xml
While testing, I discovered that animations with lots of/large masks and mattes perform *significantly* worse with hardware acceleration than software acceleration on pre-Pie devices because of RenderNode#textureUpload. It is really hard to detect this dynamically so I'm leaving the default on automatic (with an additional heuristic for >4 mattes and masks) but having an option to set it to hardware/software manually.
#381
> Add renderMode to control automatic/software/hardware acceleration

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
Discovered with tests for https://github.com/airbnb/lottie-android/pull/1083
> Prevent an OOBE in BaseKeyFrameAnimation when there are no keyframes.

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/test/java/com/airbnb/lottie/LottieCompositionFactoryTest.java
Previously, setting a null cache key could return a cached task or result. This explicitly prevents that from happening. The new tests failed before and pass now.
Fixes #1092
> Fix null cacheKeys Returning Cached Tasks

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
onAttachedToWindow and onDetachedFromWindow aren't sufficient for LottieAnimationView to properly pause and resume. We must do the same from onVisibilityChanged as well or we risk Lottie animating when the app is in the background.
Fixes #987 
Thanks @florianPOLARSTEPS
> Pause Lottie when visibility changes

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
The assumed logic for the original code was that the `else` branch is for `visibility != VISIBLE` but that isn't true if `visibility == VISIBLE` and wasAnimatingWhenVisibilityChanged is false. That caused animations to incorrectly be paused the first time they became visible when autoPlay was true.
Fixes #1123
> Fix animations starting paused when autoPlay is set to true

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java
Lottie should render the max frame. However, setting the max frame truncated it to an int so the frame itself would never render.
I can confirm that this fixes #1034. Calling `getProgress()` from `onAninmationEnd()` yielded 0.996 before and 1.0 now. The animation attached in #1034 also fully disappears by the end of the animation.
> Prevent setMaxFrame from truncating the last frame.

- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt
Now, animations with fonts will render using the system font rather than crashing.
> [Sample App] Include a default font asset delegate

- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/model/Marker.java
- lottie/src/test/java/com/airbnb/lottie/model/MarkerTest.java
> Match trailing carriage returns and ignore case for marker names

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
`onVisibilityChanged` callback will be called even when the visibilities of the ancestors of the view has changed.
So we need to check the visibility with `isShown()`, not with `visibility == View.VISIBLE` in onVisibilityChanged callback.
https://developer.android.com/reference/android/view/View#isShown()
**ex)** Assume below view hierarchy when the activity is in background.
DecorView (invisible)
...
|- FrameLayout (invisible)
|- |- LottieAnimationView (visible)
When the activity goes foreground, onVisibilityChanged callback in LottieAnimationView will be called by DecorView's visibility changing.
```java
onVisibilityChanged(DecorView /* changedView */, true /* visibility */)
```
Then, LottieAnimationView will resume animation although it is not visible by FrameLayout.
DecorView …
> Fix issues about visibility changes

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
If systemAnimationScale == 0, the lottie animation will play then immediately jump to the last frame, or only jump to the last frame if it is a loop animation. 
This solution handles if the dev move the animation at some percentage, change first or last frame or play the animation in reverse.
Really useful for testing purpose in order to not overload the main thread
Unittest are OK, I couldn't start the uiTest as it require the AWS key.
I couldn't add unittest as it obviously doesn't try to start the animations in it
There is a small Code Review here https://github.com/CmoaToto/lottie-android/pull/1
> No animation if systemAnimationScale == 0

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
In cases where LottieAnimationView is large and software rendering is used, Android may not be able to generate a bitmap large enough which causes nothing to be shown. Rather than have this happen, fall back on hardware acceleration which is supported > api 11. Potentially taking a perf hit and displaying is better than a blank screen and not displaying at all.
Encountered this where upon rotation on a tablet, the view became big enough that generation of the bitmap failed.
> Have software rendering fallback on hardware acceleration

- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
Setting `System.nanoTime()` to `lastFrameTimeNs` outside doFrame callback may lead to negative `timeSinceFrame` value. This causes the animation to end right after it started.
> Fix: incorrect System.nano() usage leads to the animation to end prematurely

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
The platform check fixes #1243 #1241 
The other logic makes `wasAnimatingWhenDetached` work even if autoPlay is false.
cc @kcoppock
> Fix old platform behavior which would prevent views from playing on attach

- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
This fixes #1199 _and_ improves performance by never saving a layer outside of the canvas. Thanks to @pmecho for the repro steps!
> Clip masks and mattes to the canvas

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
The null check added by https://github.com/airbnb/lottie-android/pull/1148 gets removed by Proguard optimization (as it is overly aggressive in removing null checks on final fields.
Use non final init member to work around Proguard removing null check on final field when optimizing.
> Fix crash on 5.x when optimizing with Proguard

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
This changes the default failure behavior for network errors to log instead of crash.
It also gives you the ability to set and clear failure listeners to handle this yourself.
Fixes #1302
> Add custom failure listener support to LottieAnimationView and log network failures

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
While the playAnimation() api call respects systemAnimationsEnabled flag, resumeAnimation() ignores it. Add the condition check to fix the case.
> Don't resume animation when system animation is disabled.

- LottieSample/src/androidTest/java/com/airbnb/lottie/samples/FragmentVisibilityTests.kt
- LottieSample/src/androidTest/java/com/airbnb/lottie/samples/LottieIdlingAnimationResource.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Additionally - adjusted "testPausesWhenScrolledOffScreenAndResumesWhenComesBack" test.
See more details: https://github.com/airbnb/lottie-android/issues/1324
> Fixed endless recycler view animation. 

- lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java
In #1368, progress calculation problem with time-remapping is fixed but it still have a possibility for rounding-off error.
I can't prepare a simple sample for reproduce, but I encount blinking issue with a company internal resource.
> Fix rounding-off error on progress calculation with time-remapped layer

- issue-repro/src/main/res/layout/activity_main.xml
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
[This](https://github.com/airbnb/lottie-android/pull/1190) change was supposed to revert to software rendering when the device can't allocate a hardware buffer large enough for the animation. However, this would also trigger before a composition loads and the view was set to wrap_content. The width and heigh would be 0 which would cause Android to noop the drawing cache. However, the previous logic here would think that the drawing cache failed to allocate because it was too large.
I also added some systrace markers and added a default animation view to the issue repro module.
Fixes #1374
> Prevent software rendering from getting overwritten

- CHANGELOG.md
- LottieSample/src/androidTest/java/com/airbnb/lottie/samples/BitmapPool.kt
- LottieSample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt
- LottieSample/src/androidTest/java/com/airbnb/lottie/samples/ObjectPool.kt
- LottieSample/src/androidTest/java/com/airbnb/lottie/samples/SuspendingSemaphore.kt
- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/DynamicActivity.kt
- LottieSample/src/main/res/drawable/ic_error.xml
- LottieSample/src/main/res/layout/activity_dynamic.xml
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/res/values/attrs.xml
This may happen either with invalid inputs or when network loading fails.
> Add a fallback resource when compositions fail to load

- lottie/src/main/java/com/airbnb/lottie/utils/GammaEvaluator.java
- lottie/src/test/java/com/airbnb/lottie/utils/GammaEvaluatorTest.java
if `startInt` and `endInt` are same valule, the method always returns `startInt` (or `endInt`) value.
> Early return for GammaEvaluator.evaluate()

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
- To improve performance of `BaseKeyframeAnimation.getCurrentKeyframe()` called by `setProgress()` of `BaseKeyframeAnimation` who has only one `Keyframe`, `SingleKeyframeWrapper` was implemented with `KeyframeWrapper` interface.
- At LottieLogo1.json, processing time of `setProgress()` was reduced about 70%.
> Add KeyframesWrapper to improve setProgress() performance

- LottieSample/src/main/kotlin/com/airbnb/lottie/samples/PlayerViewModel.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/res/values/attrs.xml
> Add the ability to set custom cache keys or set non cache key

- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
`contentPaint.alpha` is changed multiple times without reset it back. This will lead to `Utils.saveLayerCompat` call with incorrect alpha. 
In our case it should be 255, but if last mask was applied with 0 alpha (e.g. in `applyAddMask`), next draw will be transparent, because layer will be saved with 0 alpha.
Fix is to set proper alpha before saving layer.
> Fix opacity used in save layer

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
Fixes https://github.com/airbnb/lottie-android/issues/1492
> Ensure ImageView updates Drawable bounds when not using LottieAnimationView

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/res/values/attrs.xml
Fixes #1523, with an enhancement.
The issue was that the `defStyleAttr` would not be respected - the following class would compile, but `R.attr.heartViewStyle` would be ignored:
```kotlin
class HeartView(context: Context, attrs: AttributeSet)
: LottieAnimationView(context, attrs, R.attr.heartViewStyle)
```
This meant that if we had a style:
```xml
<style name="Widget.LottieSample.HeartView">
<item name="lottie_autoPlay">true</item>
<item name="lottie_loop">true</item>
<item name="lottie_url">https://raw.githubusercontent.com/airbnb/lottie-android/master/LottieSample/src/main/res/raw/heart.json</item>
</style>
```
we'd need to apply it explicitly in the layout each time we used it to a `LottieAnimationView` (or `HeartView`, but at this stage, there's no need for `HeartView` to exist - it …
> [1523] Add support for default styles to LottieAnimationView

- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
I needed to overlay the animation on the video in the background thread and I encountered a black blinking due to the presence of a shared static state in Utils
> Fix blinking black in multithreading mode

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/parser/moshi/JsonUtf8Reader.java
> Enable xml preview in Android Studio.

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
Fixes https://github.com/airbnb/lottie-android/issues/1556
> Add cacheKey to LottieCompositionFactory call

- lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java
Close #1183. Close #1310.
This has a couple of related bugfixes.
1. Fix the scale/positioning of the text relative to the parent (from PR #1583, thanks @pikaMouse)
1. Include text tracking values in the line width used for text alignment
1. Scale the text tracking values based on the font size rather than the parent size (parent size adjustment is already handled when we're calculating tracking values)
1. Include all bytes for multibyte characters when calculating canvas offsets for characters.
From #1183, here's the updated test animation result with the text correctly centered between the lines:
And here's the before and after for the same sample with some 🦁 emojis added in to show multibyte character measurement:
Before:
After:
> Fix scaling and tracking for dynamic text

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java
Fix parsing .lottie files
the dotLottie format  (dotlottie.io) is a zip file with animation.json bundled along with image resources, and manifest
**Changes**
* update zipStreamSync() to handle dotLottie use case
* ignore manifest.json otherwise lottie will try to use it
* update network loader to check for .lottie and treat it as a .zip
* add support for .lottie and in rawRes
* use magic header to determine files and use zipStreamSync() instead of fromJsonSync()
* this has the bonus side effect of allowing .zip files in rawRes as well (which doesn't appear to have been supported before)
> add support for dotLottie 

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/TextKeyframeAnimation.java
When using animated text, the last value was not shown. Issue can be reproduce with this json: https://assets7.lottiefiles.com/packages/lf20_fteywrno.json
> Display last animated text value

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- sample/src/androidTest/java/com/airbnb/lottie/samples/LottieAnimationViewTest.kt
Fixes https://github.com/airbnb/lottie-android/issues/1696
> Reset LottieDrawable when setting the same composition a second time

- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
Fixes https://github.com/airbnb/lottie-android/issues/1625
> Don't render masks or mattes of <1px

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
I can't figure out why this would happen but if it is happening, it's better to potentially have an undesirable animation missing some lazy composition tasks rather than crash.
Fixes https://github.com/airbnb/lottie-android/issues/1702
> Wrap lazy composition tasks with a null check

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- sample/src/androidTest/java/com/airbnb/lottie/samples/HappoSnapshotter.kt
- sample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt
Drawables should provide intrinsic bounds to its consumers and should respect the bounds set on it. LottieDrawable was not conforming to this because it was settings its own bounds to the composition bounds. This caused issues like that reported in https://github.com/airbnb/lottie-android/issues/1542.
Fixes https://github.com/airbnb/lottie-android/issues/1542
> Don't set LottieDrawable bounds from within itself

- lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java
> Fail quietly if ImageAssetManager fails to decode a bitmap

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- sample-compose/build.gradle
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/ComposeActivity.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/composables/AnimationRow.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/lottiefiles/LottieFilesPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/lottiefiles/LottieFilesRecentsAndPopularPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/lottiefiles/LottieFilesSearchPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/PlayerPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/ToolbarChip.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/preview/PreviewPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/showcase/ShowcasePage.kt
Upgrades Compose to Alpha 11!
I migrated some deprecated APIs, mostly related to effects. Also wrapped the player controls and toolbar in the `AnimatedVisibility` composable so toggling focus mode feels a little less jumpy.
Did some manual testing and everything looks good in the sample app 🎉 
Let me know what you think about the content descriptions for icons - I'll be happy to add some, but you tell me if it's needed!
> [Compose] Upgrade to Alpha 11

- CHANGELOG_COMPOSE.md
- README.md
Referring to #1733, also see https://github.com/airbnb/lottie/pull/151
Adds a bit of information about how to include lottie-compose snapshots.
CC @gpeal
> [Compose] Add Snapshot Dependency Documentation

- CHANGELOG_COMPOSE.md
- build.gradle
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimationState.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/lottiefiles/LottieFilesSearchPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/PlayerPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/ToolbarChip.kt
- sample-compose/src/main/res/values/strings.xml
In relation to #1734
`LottieAnimationView` had merge paths disabled by default, but `LottieAnimation` enables them by default. As long as merge paths contain known bugs, I think it makes sense not to change that behavior - what do you think?
I added a flag for it to the state. If you want, we can add it as a constructor param too, but I feel like that's not needed as it's not that commonly used.
Cheers
> [Compose] Add merge paths flag

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/res/values/attrs.xml
Good morning or afternoon, Lottie!
I created this small PR for a use case I currently have in my project. Essentially, we have a fullscreen animation that have loading and success states. When loading finishes, we play out final state of the animation and listen for Animator.AnimatorListener#onAnimationEnd to dismiss the screen.
Obviously, if user opted to disable animations the screen is stuck, because the listener method is never invoked (we add it just before playing the final state of the animation) and therefore screen is never dismissed. 
This PR provides a possibility to override current behaviour (which is just looking if animations are disabled in Settings) with custom flag in XML (false by default, so behaviour won't change) and makes LottieDrawable#setSystemAnimationsAreEnabled …
> Added override for system animations enabled behavior

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
This makes LottieAnimation modifiers behave as they are supposed to given the [Compose guidelines](https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md)
Fixes #1761
> [Compose] Swap Modifier order

- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/PlayerPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/utils/BitmapUtils.kt
Now, when an image is missing, it will be rendered with a gray box
> [Compose Sample] Add bitmaps and dummy bitmaps to the sample app

- CHANGELOG_COMPOSE.md
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieDynamicProperties.kt
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/ComposeActivity.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/Route.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/examples/DynamicPropertiesExamplesPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/examples/ExamplesPage.kt
https://github.com/airbnb/lottie-android/pull/1820 but built on top of https://github.com/airbnb/lottie-android/pull/1827
Example usage can be seen on DynamicPropertiesExamplesPage.kt.
Thanks to Compose's impressive snapshot system, states that are read during the drawing pass via the dynamic properties callback are automatically registered so invalidation happens correctly by default.
> [Compose] Added the ability to set dynamic properties V2

- .idea/jarRepositories.xml
- build.gradle
Let's see if this fixes the deployment issue 
https://github.com/airbnb/lottie-android/runs/3002049947?check_suite_focus=true
May fix #1837
> Add jetbrains maven repo and upgrade the publish plugin

- lottie-compose/src/main/java/com/airbnb/lottie/compose/animateLottieCompositionAsState.kt
I added the option to set cancellation behavior on `animateLottieCompositionAsState` instead of relying on the default value from `LottieAnimatable.animate`. It's a pretty useful setting that allows me to easily implement my loading animation that includes success and failure transitions.
> Add cancellation behavior to animateLottieCompositionAsState

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimatable.kt
- lottie-compose/src/test/java/com/airbnb/lottie/compose/LottieAnimatableImplTest.kt
> [Compose] Ensure LottieClipSpec is always respected

- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/composables/Loader.kt
Initial loader would stop after a Single iteration.
Changed to Infinite.
Prev #1851
> Fix loading animation

- build.gradle
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieCompositionSpec.kt
> [Compose] Make LottieCompositionSpec an inline class

- sample-compose/build.gradle
- sample/build.gradle
https://github.com/airbnb/lottie-android/pull/1874/ broke instrumentation tests:
1) Espresso broke with [this erro](https://github.com/airbnb/lottie-android/pull/1874/). It can probably be fixed by upgrading androidx test core but then there is a dependency conflict error which can probably be fixed by upgrading `androidx.fragment:fragment-testing` but there isn't a version of it that depends on test core 1.4.0.
2) The upgraded AWS SDK returns multiple status from the listener which caused the await continuation to be already resumed. I don't have time to debug the full behavior change and the old one was working fine.
> Downgrade espresso and AWS

- .github/workflows/validate.yml
Fixes https://github.com/airbnb/lottie-android/pull/1875. After this change, workflows were running twice on PRs.
> [CI] Only run validate workflow on pushes to master

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieCompositionSpec.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt
Using LottieTask under the hood incurred several extra thread hops including a main thread post. Switching it to a result like this is both faster and also enables custom factories to be used. From my initial tests, this cut the parse time for the heart animation in the repo roughly in half.
Unfortunately, LaunchedTask takes a few ms to start. I tried with `rememberCoroutineScope().launch` and the initial delay was the same so I'm not sure if there is anything else that can be done here.
Fixes https://github.com/airbnb/lottie-android/issues/1880
> [Compose] Parse LottieComposition synchronously instead of using LottieTask

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieCompositionSpec.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt
Reverts airbnb/lottie-android#1888
This was not a good solution. It lost task joining so requesting the same animation multiples would parse the animation multiple times.
> Revert "[Compose] Parse LottieComposition synchronously instead of using LottieTask"

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieCompositionSpec.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt
This builds on the revert in https://github.com/airbnb/lottie-android/pull/1890 and leverages the task joining behavior of LottieCompositionFactory to synchronously initiate the task when the composition first runs so that it can then be joined to immediately retrieved whenever the LaunchedEffect runs.
> [Compose] Warm the task cache before LaunchedEffect runs

- lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java
Previously, the calculation of `endLength` could suffer from rounding errors. While most of the time, these errors are not a big deal, when the end value is 100, this can result in `endLength` being larger than `totalLength`, causing unexpected behavior where the animation reverts to an initial state when it should be showing the final state. By forcing the order of operations, we can get the answer we expect / need.
For example:
```kotlin
val totalLength = 98.164566
totalLength * 100f / 100f // 98.16457
totalLength * (100f / 100f) // 98.164566
```
Unfortunately, I have been unable to get a simple animation to reproduce this error, and the complex one I am using is not really available for public sharing. However, it seems like this should be a safe change.
> Enforce order of operations to avoid rounding errors

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
This PR contains a small typo fix in the documentation of the `LottieAnimation` composable.
Thank you for the great library and the Compose support! 🙏
> Fix a typo in the Compose LottieAnimation docs

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/TransformKeyframeAnimation.java
Although me and the reporters are unable to reproduce these NPEs, it's not impossible that they would occur if either:
* LottieDrawable's composition is set multiple times from multiple threads
* Dynamic properties are set from multiple threads
This adds some thread safety to variable access and should resolve these.
Fixes https://github.com/airbnb/lottie-android/issues/1794
> Fix a few potential NPE race conditions

- issue-repro/build.gradle
Fixes an issue in which Kotlin code wasn't being compiled and the issue-repro module insta crashed unable to find IssueReproActivity
> Add kotlin-android back to issue-repro

- lottie/src/main/java/com/airbnb/lottie/animation/LPaint.java
- lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java
- lottie/src/main/java/com/airbnb/lottie/animation/content/FillContent.java
Resolves #1928 
This pull request attempts to remove ColorSpace.Named[] allocations when calling Paint.setAlpha(). These changes will fix the issue only when using RGB colors.
> Replaced Paint.setAlpha() with Paint.setColor() to reduce unnecessary allocations

- gradle.properties
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/RenderMode.java
- sample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt
- sample/src/main/res/layout/player_fragment.xml
- snapshot-tests/src/main/AndroidManifest.xml
This change marks a significant change in the underlying rendering pipeline for Lottie.
Previously, Lottie would always set a layerType on LottieAnimationView. For hardware accelerated animations, this meant that a separate graphics layer was allocated for the animation. The disadvantage with this method is that the texture has to be uploaded separately to the GPU on each frame.
For software rendering, Lottie would depend on Android's view caching mechanism in which View allocates a drawing cache bitmap which it then draws to a canvas. This has the disadvantage of the Bitmap always being the size of the containing View even if it's larger than the drawable.
It also abstracts away the Bitmap so that further optimizations. When software rendering is enabled and it has to be redrawn without …
> Replace LottieAnimationView layer types with internal bitmap rendering

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
This PR addresses the issue #1958 , although the crash is pretty hard to reproducible, the enhancement will definitely make it more robust.
The issue was in `com.airbnb.lottie.LottieDrawable#buildCompositionLayer` method.
The related code is:
```
private void buildCompositionLayer() {
compositionLayer = new CompositionLayer(
this, LayerParser.parse(composition), composition.getLayers(), composition);
if (outlineMasksAndMattes) {
compositionLayer.setOutlineMasksAndMattes(true);
}
}
```
The crash exception stack prints:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.airbnb.lottie.LottieComposition.getLayers()' on a null object reference
at com.airbnb.lottie.LottieDrawable.buildCompositionLayer(LottieDrawable.java:298)
...
```
As we …
> Fix a potential NPE race conditions

- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
It's possible for the screen density to change when moving between windows or screens. In this case lottie renders animations the wrong size. Android already does a pretty good job of caching and updating the system context so just let it do it's job.
I am currently relying on reflection to clear this field on a configuration change and I'd of course like to remove that.
I haven't had time to come up with a generic repro, but I thought I'd open this anyway. Sorry.
> Don't cache dpScale in Utils

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieCompositionSpec.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt
This adds a new `LottieCompositionSpec` option to load an animation from a content provider URI. This wasn't needed pre-Compose because you could get the input stream and parse the animation using that. However, Lottie Compose doesn't provide a direct API to parse an animation from an input stream. It doesn't expose that because a closeable input stream isn't a great candidate to put in a data class and makes `LottieCompositionSpec` stateful and closeable.
I also noticed some inconsistency in the way cache keys were handled for other specs so I fixed those as well.
Fixes #1978
> [Compose] Add LottieCompositionSpec.ContentProvider

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/java/com/airbnb/lottie/LottieTask.java
Also did some routine code cleanup in surrounding code.
Fixes https://github.com/airbnb/lottie-android/issues/1971
> Fix a rare LottieTask leak

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimatable.kt
- sample-compose/build.gradle
- sample-compose/src/androidTest/java/com/airbnb/lottie/samples/InfiniteAnimationTest.kt
You can see how androidx handles this in AndroidTestComposeRule [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-test-junit4/src/androidMain/kotlin/androidx/compose/ui/test/junit4/AndroidComposeTestRule.android.kt;l=187?q=InfiniteAnimationPolicy%20lang:kotlin).
Fixes https://github.com/airbnb/lottie-android/issues/1907
> [Compose] Prevent infinite Lottie animations from preventing tests from going idle

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- sample/src/androidTest/java/com/airbnb/lottie/samples/FragmentVisibilityTests.kt
Previously, all of the logic to pause/resume Lottie animations on events such as hiding a view, backgrounding an app, etc. were handled by LottieAnimationView. This logic works fine for the default cause. However, LottieDrawable had no notion of visibility handling itself. As a result, if somebody were to use LottieDrawable on its own, they would have to get the lifecycle exactly right or else they could risk leaking animators and impacting the user's battery life.
This PR combines all of the logic into Drawable.setVisible. This also simplifies things because it is a single API vs views that have to deal with window attachment and visibility changes.
I ran all existing FragmentVisibilityTests and they all pass and the intention is to maintain backwards compatibility.
> Move window/view visibility handling from LottieAnimationView to LottieDrawable

- .idea/codeStyles/Project.xml
- .idea/inspectionProfiles/Project_Default.xml
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieDynamicProperties.kt
- lottie/src/main/java/com/airbnb/lottie/LottieProperty.java
- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/TextKeyframeAnimation.java
- lottie/src/main/java/com/airbnb/lottie/model/DocumentData.java
- lottie/src/main/java/com/airbnb/lottie/model/KeyPath.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/TextTestCase.kt
The original TextDelegate API pre-dates dynamic properties. Compose only has access to the newer dynamic properties API so this PR extends dynamic property support to include text.
```kotlin
val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.name))
val progress by animateLottieCompositionAsState(composition, iterations = LottieConstants.IterateForever)
val dynamicProperties = rememberLottieDynamicProperties(
rememberLottieDynamicProperty(LottieProperty.TEXT, "Gabriel Peal", "NAME"),
)
LottieAnimation(
composition,
progress,
dynamicProperties = dynamicProperties,
)
```
Fixes https://github.com/airbnb/lottie-android/issues/1903
> Add support for text in dynamic properties

- CHANGELOG_COMPOSE.md
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
The correct value for merge paths must be set before setting the composition.
Fixes https://github.com/airbnb/lottie-android/issues/1970
> [Compose] Set merge paths before the composition

- CHANGELOG.md
- lottie/src/main/java/com/airbnb/lottie/model/Marker.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/SnapshotTestCaseContext.kt
Fixes https://github.com/airbnb/lottie-android/issues/1990
> Add getters for Marker fields

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimatable.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieConstants.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/animateLottieCompositionAsState.kt
- lottie-compose/src/test/java/com/airbnb/lottie/compose/LottieAnimatableImplTest.kt
This will _only_ automatically work for `animateLottieCompositionAsState(...)` because accessing the system animator scale requires a Context and the coroutines `LottieAnimatable` functions don't have access to that. Apps will need to manually handle the scale if they aren't using `animateLottieCompositionAsState(...)`.
When animations are disabled, the speed becomes infinite and Lottie will jump to the end of the animation.
Fixes https://github.com/airbnb/lottie-android/issues/1906
> [Compose] Respect system animator scale

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
To reproduce crash, add the following to the IssueReproActivity:
```
binding.animationView.setCacheComposition(false)
binding.animationView.renderMode = RenderMode.SOFTWARE
binding.animationView.postDelayed({ binding.animationView.setAnimation(R.raw.heart) }, 1000)
```
When it tries to render with null composition, `getIntrinsicWidth()` and `getIntrinsicHeight()` return `-1`, and both `renderWidth` and `renderHeight` end up being negative, which results in a crash:
```
java.lang.IllegalArgumentException: width must be > 0
at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:378)
at android.graphics.Bitmap.createBitmap(Bitmap.java:684)
at android.graphics.Bitmap.createBitmap(Bitmap.java:653)
at com.airbnb.lottie.LottieDrawable.ensureSoftwareRenderingBitmap(LottieDrawable.java:1452)
at …
```
> Check composition exists when using software rendering

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/value/LottieValueCallback.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/LottieSnapshotTest.kt
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/SoftwareRenderingDynamicPropertiesInvalidationTestCase.kt
The test case failed to re-render before but works now.
> Allow software rendering to be invalidated when dynamic properties change

- lottie/src/main/java/com/airbnb/lottie/network/DefaultLottieFetchResult.java
- lottie/src/main/java/com/airbnb/lottie/network/DefaultLottieNetworkFetcher.java
- lottie/src/main/java/com/airbnb/lottie/network/FileExtension.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkCache.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java
- lottie/src/main/java/com/airbnb/lottie/network/package-info.java
Fixes https://github.com/airbnb/lottie-android/issues/2046
> Fix RestrictTo permissions for the networking package

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimatable.kt
- sample-compose/src/androidTest/java/com/airbnb/lottie/samples/WalkthroughAnimationTest.kt
The change in #1987 to always use `withInfiniteAnimationFrameNanos` prevents non-infinite animations from completing in Compose tests. 
I added a simple check to use `withFrameNanos` or `withInfiniteAnimationFrameNanos` based on the number of iterations. This fixes tests that wait for animations to complete, see sample `WalkthroughAnimationTest`. And `InfiniteAnimationTest` still passes.
Let me know if I'm missing some other use case.
> Support completable animations in Compose tests

- CODE_OF_CONDUCT.md
I assume these were copy-paste errors, so I just replaced the mentions of Store to Lottie, since I assume that was unintended. :)
> Fix references to Store in Code of Conduct

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
Previously, the start function would be a noop if your callback was something other than a View instance.
With this change, if you use a non-View Callback (such as a Drawable), start will still call playAnimation; if the Callback was a View, it must still not be in edit mode to call playAnimation.
> Fix LottieDrawable#start for non-View callbacks

- sample/src/main/kotlin/com/airbnb/lottie/samples/ShowcaseFragment.kt
- sample/src/main/kotlin/com/airbnb/lottie/samples/model/ShowcaseItem.kt
- sample/src/main/kotlin/com/airbnb/lottie/samples/views/ShowcaseDemoItemView.kt
This PR fixes #2029 which refers to two memory leaks leading to the leak of `ShowcaseFragment`.
* For fixing 1st memory leak in the issue we have used `requireActivity` inside for each loop as an explicit field outside the lambda which introduces a synthetic field of activity thus avoiding leak. You can compare this with the previous screenshot attached to the [issue](https://github.com/airbnb/lottie-android/issues/2029). This is inside [this](https://github.com/airbnb/lottie-android/commit/5d0893a82ed376967900bdb9323216994ee64de0) commit.
* For fixing 2nd memory leak we have added explicit context as a parameter in `clickListener` high order function field of `ShowcaseItem`. Correctly passing the application context to this removes the memory leak. This is inside …
> Fixing memory leak of ShowcaseFragment

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
> Make LottieDrawable.setSystemAnimationsAreEnabled public

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
The root cause of #2053 is that once the fragment was paused and resumed, the onResumeAction was set to RESUME and never cleared. The compass view in the linked project triggered a relayout on every frame which caused the visibility action run over and over again. The animation itself happens to have an empty first frame so it appeared as if the animation disappeared.
Fixes #2053
> Clear onVisibleAction once the action is taken

- issue-repro-compose/src/main/java/com/airbnb/lottie/issues/compose/ComposeIssueReproActivity.kt
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/examples/AnimatableExamplesPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/examples/BasicUsageExamplesPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/examples/TransitionsExamplesPage.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/examples/ViewPagerExample.kt
- sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/PlayerPage.kt
Fixes #2077
This issue can be fixed by a very simple approach mentioned in [https://developer.android.com/jetpack/compose/performance#defer-reads](Compose performance docs - Defer reads as long as possible) by deferring the progress read to the draw function.
Also, I've updated samples in this repo to use the new approach.
> Fix LottieAnimation recomposes on every frame degrading performance

- lottie/src/main/java/com/airbnb/lottie/parser/GradientColorParser.java
- lottie/src/test/java/com/airbnb/lottie/parser/GradientColorParserTest.java
Refer to code comments for more info:
Before:
After:
> De-dupe gradient stops

- lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java
In Android docs, BitmapFactory.decodeStream may return NULL, This is a legal return value, we did not deal with it, NPE may occur in some cases. So I fixed it.
> Fix ImageAssetManager.bitmapForId NPE crash

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
This PR updates the javadoc of `LottieAnimationView#setRenderMode` to be in line with the [implementation](https://github.com/airbnb/lottie-android/blob/c553ad392e62f29de7045f4e5c9ed116d951c454/lottie/src/main/java/com/airbnb/lottie/RenderMode.java#L27-L34)
> Update documentation to be in line with behavior

- lottie/src/main/java/com/airbnb/lottie/L.java
- lottie/src/main/java/com/airbnb/lottie/Lottie.java
- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/java/com/airbnb/lottie/LottieConfig.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java
**Rationale**
We'd like to implement more sophisticated caching strategy for animations fetched from network. This could be implemented on the network fetcher level e.g. using the OkHttp's cache or the "stale-while-revalidate" strategy.
For this to work the internal Lottie network cache has to be completely disabled.
The option to do so is implemented in this PR.
**Implementation**
By default the internal cache is enabled to maintain backward compatibility. 
We've added the `LottieConfig.Builder.setEnableNetworkCache()` method to override the default behavior.
> Add the LottieConfig.Builder.setEnableNetworkCache() method to completely disable internal network cache if needed

- lottie/src/main/java/com/airbnb/lottie/animation/content/ContentGroup.java
- lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java
- lottie/src/main/java/com/airbnb/lottie/model/animatable/AnimatableTransform.java
- lottie/src/main/java/com/airbnb/lottie/model/content/CircleShape.java
- lottie/src/main/java/com/airbnb/lottie/model/content/ContentModel.java
- lottie/src/main/java/com/airbnb/lottie/model/content/GradientFill.java
- lottie/src/main/java/com/airbnb/lottie/model/content/GradientStroke.java
- lottie/src/main/java/com/airbnb/lottie/model/content/MergePaths.java
- lottie/src/main/java/com/airbnb/lottie/model/content/PolystarShape.java
- lottie/src/main/java/com/airbnb/lottie/model/content/RectangleShape.java
- lottie/src/main/java/com/airbnb/lottie/model/content/Repeater.java
- lottie/src/main/java/com/airbnb/lottie/model/content/RoundedCorners.java
- lottie/src/main/java/com/airbnb/lottie/model/content/ShapeFill.java
- lottie/src/main/java/com/airbnb/lottie/model/content/ShapeGroup.java
- lottie/src/main/java/com/airbnb/lottie/model/content/ShapePath.java
- lottie/src/main/java/com/airbnb/lottie/model/content/ShapeStroke.java
- lottie/src/main/java/com/airbnb/lottie/model/content/ShapeTrimPath.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/ShapeLayer.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java
This allows GradientFill to access the composition directly. Previously, when accessed through LottieDrawable, there was a potential race condition that caused LottieDrawable.getComposition() to be set to something else externally before the GradientFill content was able to access it.
Fixes #2159
> Pass LottieComposition to all content when it is generated

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
See [#2069](https://github.com/airbnb/lottie-android/issues/2069)
> Fix LottieAnimationView.setProgress called from the view init method prevents the progress from being restored from the saved state

- build.gradle
gradlePluginPortal is backed by jcenter which is down again and going away.
> Migrate gradlePluginPortal to mavenCentral

- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
It isn't clear why the underlying issue is happening but if it's isolated and device specific, it's easier to add this harmless checking code rather than get to the bottom of this one.
Fixes https://github.com/airbnb/lottie-android/issues/2083
> Add NPE protections around transform opacity

- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/SnapshotTestCaseContext.kt
This should give better test coverage of glyphs and font rendering.
> [Snapshot tests] Only set a font asset delegate when there are no glyphs

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/TextTestCase.kt
Fixes https://github.com/airbnb/lottie-android/issues/2119
> Allow setting a map of typefaces instead of a callback

- lottie/src/main/java/com/airbnb/lottie/model/layer/Layer.java
I'm running tests against my animation json files and I want to make sure that all the layers I expect to be there are actually there, but I'm hitting issues with the visibility of these two functions.
> Make Layer name and refId public

- lottie/src/main/java/com/airbnb/lottie/L.java
- lottie/src/main/java/com/airbnb/lottie/Lottie.java
- lottie/src/main/java/com/airbnb/lottie/LottieConfig.java
- lottie/src/main/java/com/airbnb/lottie/parser/KeyframeParser.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/LottieSnapshotTest.kt
This should prevent the large diffs in the snapshot tests
> [Snapshot tests] Disable the path interpolator cache

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
This PR fixes the stream not closing when the lottie animation hits the cache.
> Fixed the stream was not closed when the lottie animation hit the cache

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
> Allow for non-closing input stream parsing

- lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java
I think the root problem for #2281 is that there are 182 720p images played a bitmap sequences. However, while looking into it, I did discover this Context comparison issue. However, the 182 720p images are the real issue for the animation in #2282.
> Check for Application context when comparing contexts for ImageAssetManager

- issue-repro/src/main/res/layout/issue_repro_activity.xml
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- lottie/src/main/java/com/airbnb/lottie/AsyncUpdates.java
- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieThreadFactory.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieTrace.java
- lottie/src/main/res/values/attrs.xml
- sample/src/main/kotlin/com/airbnb/lottie/samples/LottieApplication.kt
- sample/src/main/res/layout/player_fragment.xml
This is the first MVP of async updates. This project is being funded by Airbnb Eng and likely wouldn't happen without their sponsorship.
The docs for the AsyncUpdates enum includes details on what is going on here but at a high level, Lottie has two hot paths:
1. setProgress
2. draw
This allows the former to happen off of them main thread _ immediately after_ draw completes so it is ready before the next one starts.
In many of my tests, the two paths were each accountable for ~50% of the total main thread work so this could reduce the main thread activity by ~50% or more.
Here is an example of systrace before:
You can see setProgress being called immediately before draw.
This is what it looks like with async updates enabled:
You can see that draw happens first and then setProgress for the …
> [Async Updates] First MVP of Async Updates

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Fixes https://github.com/airbnb/lottie-android/issues/2292
I followed `LeakCanary` hints, identified 2 listeners that were kept in the static map and fixed them by holding a weak reference to a target object (using private static classes). 
As far as I understood the flow, there should be no behavior change, other than not having a memory leak. The view can be immediately garbage collected, without altering existing behavior (the resource will continue being fetched in background).
> Do not hold strong reference to LottieAnimationView in success/failure listeners

- sample/src/main/kotlin/com/airbnb/lottie/samples/LottiefilesFragment.kt
In order to fix the issue, i needed to tweak with the getRefreshKey method which makes sure it returns a valid Int value. Earlier it was throwing a ClassCastException . But now, the method calculates & returns a refresh key based on the current state of paging data. It uses the anchor position to find the closest page, then checks if there is a previous key available. If there is, it increments it by 1. If the previous key is null, it checks if there is a next key available. If there is, it decrements it by 1. The resulting value represents the refresh key or null if both previous and next keys are null.
Before: 
https://github.com/airbnb/lottie-android/assets/8761426/4d24bbcf-44a1-4011-902a-da3b582e437f
After: 
https://github.com/airbnb/lottie-android/assets/8761426/b9efebb6-534c-4b89-a35 …
> [Sample] Handle crash issue after tapping on the Search Tab.

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
IllegalArgumentException is thrown when creating bitmap in ensureSoftwareRenderingBitmap() if the getIntrinsicWidth or getIntrinsicHeight returns -1. So, returns when renderWidth or renderHeight is negative to avoid the crash
Fixes https://github.com/airbnb/lottie-android/issues/2350
> Fix IllegalArgumentException when createBitmap

- lottie/src/main/java/com/airbnb/lottie/network/NetworkCache.java
In an app that I maintain, a crash was reported in Crashlytics indicating that there was a NPE in the Lottie library code.
It took me a bit to realize why the NPE was being caused by trying to read the length of a null array, but then I realized, the for loop calls `parentDir.listFiles()` again to iterate over rather than using the `files` array that was just checked the line above.
The changes are quite minor and should fix the problem of the NPE, that being said there may be other concerns that I'm not aware of.
> Fix Potential NPE In NetworkCache.clearCache

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/SolidLayer.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/DynamicPropertiesTestCase.kt
Fixes https://github.com/airbnb/lottie-android/issues/2362
> Add clearValueCallback and COLOR value callback to solid layer

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/test/java/com/airbnb/lottie/LottieCompositionFactoryTest.java
Fixes https://github.com/airbnb/lottie-android/issues/2360
> Check cache for LottieCompositionFactory sync methods

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ColorKeyframeAnimation.java
It is not clear to me why or how this would happen. endFrame is technically nullable because of the order that parsing happens but it should be non-null by the time parsing finishes. This should be safe enough to add to fix this NPE though.
Fixes #2361
> Fix a NPE in ColorKeyframeAnimation

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
> Add a LottieAnimationView overload for ZipInputStream

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottiePainter.kt
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/LottieSnapshotTest.kt
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/PainterTestCase.kt
This allows Lottie to be used with anything that accepts a `Painter` (like `Image`).
Fixes https://github.com/airbnb/lottie-android/issues/2193
> [Compose] Add LottiePainter

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
This allows to use the safeModeApi in LottieAnimation for compose 
Fixes #2452
> [Compose] Add safeMode

- lottie/src/main/java/com/airbnb/lottie/LottieTask.java
I investigated leaks with `RememberLottieComposition` and `LottieAnimationView`, initially thinking that we might need to stop listening to LottieTask when a view or composition gets detached / removed.
However, after looking at a heap dump, I realized that the LottieTask was actually finished. It had delivered its result so it didn't have any reason to stay in memory.
This moved my suspicion to SynchronousQueue as Android has had issues with queues & worker threads on several occasions (see code for details).
Also updated the cached thread pool to create threads named "lottie".
Leaks:
```
┬───
│ GC Root: Thread object
│
├─ java.lang.Thread instance
│    Leaking: UNKNOWN
│    Retaining 6.2 MB in 181913 objects
│    Thread name: 'pool-88-thread-2'
│    ↓ Thread<Java Local>
│ …
```
> Fix LottieTask leak

- lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
Fixes https://github.com/airbnb/lottie-android/issues/2464
> Respect autoPlay when setting a new composition

- lottie/src/main/java/com/airbnb/lottie/network/FileExtension.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkCache.java
- lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java
In addition to [#2435](https://github.com/airbnb/lottie-android/pull/2435), added support for loading gziped and tgs files from the network, similar to zip files.
> Add support for gzipped and tgs files from network

- lottie/src/main/java/com/airbnb/lottie/LottieTask.java
When we are already on the main thread, there is no need to post listeners to the main thread again.
As a side effect, this fixes https://github.com/airbnb/lottie-android/issues/2449. The listener was called twice because it was called synchronously in addListener because it was already done and then because of the post, it was called again.
Fixes https://github.com/airbnb/lottie-android/issues/2449
> Call LottieTask listeners synchronously when already on the main thread

- .github/workflows/validate.yml
- build.gradle
- lottie-compose/api/lottie-compose.api
- lottie-compose/build.gradle
- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- versions.properties
Fixes https://github.com/airbnb/lottie-android/issues/2448
> Add a binary compatibility check

- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
This was a simple logic bug that made the scale always 1.0
Fixes https://github.com/airbnb/lottie-android/issues/2216
> Fix image scaling when the display scale changes

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
> Add an additional null check in BaseKeyframeAnimation

- lottie/src/main/java/com/airbnb/lottie/L.java
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java
- lottie/src/main/java/com/airbnb/lottie/animation/content/FillContent.java
- lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java
- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java
- lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
[issue#2493]( https://github.com/airbnb/lottie-android/issues/2493)
> Prevent trace strings from getting created when tracing is disabled

- lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
- lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java
Currently, I am encountering a similar issue to [#1200](https://github.com/airbnb/lottie-android/issues/1200), but in the case where the asset is a base64 image, it has not been fixed yet.
> Fix base64 image asset not fit container's size

- lottie/src/main/java/com/airbnb/lottie/animation/content/FillContent.java
- lottie/src/main/java/com/airbnb/lottie/model/content/LBlendMode.java
- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
This commit improves blend mode support in lottie-android in two ways:
* Applying blend modes on layer-level, instead of fill level
* Adding support for the Multiply blend mode
The Lottie format defines blend modes as attributes on a layer. However, lottie-android is presently applying the layer blend modes on a solid color fill only. Notably, this causes any stroked or gradient-filled shapes or image layers to blend incorrectly, such as in this file:
[stroke-blending-test.json](https://github.com/user-attachments/files/16346206/stroke-blending-test.json)
(The file contains a filled + stroked shape that renders as a pink square on other platforms, but renders with a visible stroke on lottie-android since its blend mode is applied only on the fill.)
Instead, we move this decision to …
> Apply blend modes on layer level and add Multiply blend mode

- lottie-compose/src/test/java/com/airbnb/lottie/compose/LottieClipSpecTest.kt
- lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
- lottie/src/main/java/com/airbnb/lottie/parser/LottieCompositionMoshiParser.java
- lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java
- lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java
Use case: I just want to know the unscaled original height / width of the LottieAnimation. I want to do my own scaling by calculating for instance given an aspect ratio or weighted settings, how big/small I can stretch the animation.
> LottieComposition: Add getUnscaledHeight & getUnscaledWidth functions.

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/PathKeyframeAnimation.java
A value callback was not called, when only single value is defined for keyframe in PathKeyframeAnimation.
This PR also adds the check for startValue and endValue at start, same way it is done for other types of KeyframeAnimation.
> Fix value callback is not called for PathKeyframeAnimation

- lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
Our changes in https://github.com/airbnb/lottie-android/pull/2536 didn't work for `LottieAnimation` in compose. While LottieAnimation does use LottieDrawable, it has it's own animator and draws on canvas directly. 
This PR addresses that issue by making some logic of reduce motion readable outside LottieDrawable and consuming that logic in `LottieAnimation` 
I tested this by adding a sample lottie file with reduce motion marker locally, see the attached video. 
https://github.com/user-attachments/assets/eb33333f-86b8-46fa-9bbb-82bff8a8c7fe
> [a11y] Adding reduce motion logic to LottieAnimation for compose usage

- lottie/src/main/java/com/airbnb/lottie/animation/keyframe/SplitDimensionPathKeyframeAnimation.java
Use proper values for keyframe progress for value callbacks instead of the keyframeProgress from function arguments which is always zero.
> Fix SplitDimensionPathKeyframeAnimation value callbacks arguments

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- lottie/src/main/java/com/airbnb/lottie/configurations/reducemotion/ReducedMotionOption.java
- lottie/src/main/java/com/airbnb/lottie/configurations/reducemotion/SystemReducedMotionOption.java
- lottie/src/main/java/com/airbnb/lottie/utils/Utils.java
When calling reduce motion check we need to pass context, we read context in LottieDrawable using `getContext` method. getContext method can return a nullable context, since the code is in java we don't get any compile time error when passing the null context around. 
This resulted in issue where we end up calling `getContentResolver` on a null object in case where context is null. https://github.com/airbnb/lottie-android/pull/2536
This PR fixes it by adding a null check before calling `Utils.getAnimationScale(context)`
> Adding null check for context before calling `Utils.getAnimationScale`

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
Turns out the Compose draw path was never actually respecting safeMode
Fixes #2500
> [Compose] Fix safe mode for Compose

- lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
This PR adds the check for matte layer name before going deeper during key path resolution.
Without the fix the key path matches children inside the matte layer even though it should not, for example:
'layer_1.group_1.child_1' could match 'layer_1.**matte_1**.group_1.child_1'
With the fix it is not possible anymore.
> Fix resolving key path for matte layers

- lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
- snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/SeekBarTestCase.kt
Should move the image to the right place before scaling it.
> Apply left/top bounds before scaling

- lottie/src/main/java/com/airbnb/lottie/value/Keyframe.java
- lottie/src/test/java/com/airbnb/lottie/value/KeyframeTest.java
This fixed a really tricky bug that led to the wrong keyframe being used due to a floating point rounding error.
Given specific composition start frames and the existing floating point rounding, you could wind up with the following situation:
* Keyframe 1 has an endFrame of 48 and an endProgress of 0.095051385
* Keyframe 2 has a startFrame of 48 and a startProgress of 0.09505139
The [Keyframe.containsProgress](https://github.com/airbnb/lottie-android/blob/master/lottie/src/main/java/com/airbnb/lottie/value/Keyframe.java#L140) check intentionally leaves the upper end of the range open to make it unambiguous that the progress on the boundary of two keyframes should use the latter one.
However, due to this floating point error, there was a gap and if the progress == the endProgress of the …
> Fix floating point errors calculating keyframe end progress

- lottie/src/main/java/com/airbnb/lottie/model/layer/ImageLayer.java
The recent [improvements to drop shadows](https://github.com/airbnb/lottie-android/pull/2548/files#diff-31e777f53a917d69dcf1b234ae6c77db843316c34911e200d0a9a160c058b621R110) added a dereference of a nullable result from the `getBitmap()` call.
Fixes #2601
> Prevent NPE in ImageLayer.getBounds()

- lottie/src/main/java/com/airbnb/lottie/model/layer/ImageLayer.java
The changes in https://github.com/airbnb/lottie-android/pull/2578 set the bounds returned by `ImageLayer.getBounds()` to have 0 width and 0 height if there is no Bitmap available. This change instead calls the previous version of the logic which reads the width and height of the `LottieImageAsset`.
> Partially revert previous change to ImageLayer.getBounds()

- lottie/src/main/java/com/airbnb/lottie/utils/OffscreenLayer.java
Fixes https://github.com/airbnb/lottie-android/issues/2620, which only occurs on Android 12 devices.
See [my branch](https://github.com/airbnb/lottie-android/compare/master...allenchen1154:lottie-android:allen--bitmap-crash-repro?expand=1) for a repro example.
With the fix:
https://github.com/user-attachments/assets/19fcd7b4-9a11-4200-80fb-0868cd62b0d4
> Guard against Bitmap allocations of size 0

- lottie-compose/build.gradle
- lottie/build.gradle
- versions.properties
See [Sonatype documentation](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/) for more details on the differences. The current publishing method (OSSRH) is being sunset on June 30th, 2025. New users can no longer be onboarded to the Nexus Repository Manager, which means they must use the newer Central Portal to publish.
See [plugin documentation](https://vanniktech.github.io/gradle-maven-publish-plugin/central/#configuring-maven-central) for more details.
This will require developers to generate new tokens on Sonatype, as the old OSSRH tokens will no longer work.
> Publish to central.sonatype.com

- lottie/src/main/java/com/airbnb/lottie/network/DefaultLottieFetchResult.java
The getErrorFromConnection() method attempts to construct an InputStreamReader, passing in HttpURLConnection.getErrorStream() as the constructor's arg. According to the doc for HttpURLConnection.getErrorStream(), this method can return null if there have been no errors, the connection is not connected or the server sent no useful data. The InputStreamReader(InputStream) constructor passes its arg to java.io.Reader, and that class throws an NPE if the arg is null.
> In DefaultLottieFetchResult, catch NPE from getErrorFromConnection()

- lottie-compose/api/lottie-compose.api
- lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt
`lottieComposition(..)` is now public.  
This is helpful when you want to ensure the LottieComposition is loaded before triggering any state changes in a suspendable function or complex LaunchedEffect
> Make `lottieComposition` public
