README.md

the assets folder is located in app/src/main/ therefore res/assets will confuse some people.

updated assets folder location in readme.

---

LottieSample/src/main/java/com/airbnb/lottie/samples/AppIntroActivity.java

fix : close AppIntroActivity when DONE pressed

---

README.md

Added a link to the Titanium Android module for Lottie

Adding Titanium module

---

lottie/src/main/java/com/airbnb/lottie/AnimatableFloatValue.java
lottie/src/main/java/com/airbnb/lottie/AnimatableIntegerValue.java
lottie/src/main/java/com/airbnb/lottie/FloatKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/IntegerKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/LayerView.java
lottie/src/main/java/com/airbnb/lottie/ShapeLayer.java

More can be done but this is a good start.
#123

Reduce memory overhead by eliminating some unboxing and iterator creation

---

lottie/src/main/java/com/airbnb/lottie/LottieComposition.java

Use Thread Pool executor for AsyncTasks

---

lottie/src/main/java/com/airbnb/lottie/AnimatableGradientColorValue.java
lottie/src/main/java/com/airbnb/lottie/ContentGroup.java
lottie/src/main/java/com/airbnb/lottie/GradientColor.java
lottie/src/main/java/com/airbnb/lottie/GradientColorKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/GradientFill.java
lottie/src/main/java/com/airbnb/lottie/GradientFillContent.java
lottie/src/main/java/com/airbnb/lottie/ShapeGroup.java

Initial support for linear gradients

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

* Allow playAnimation() to mimic behavior of resumeAnimation(), if and only if, progress has occured.
Signed-off-by: Brandon McAnsh <brandon.mcansh@gmail.com>
Before opening a pull request:
* If you added a new feature or fixed a bug, add a json file to assets/Tests and add a test 
for it in `LottieTest#testAll`.
* Run screenshot tests by running `./gradlew --daemon recordMode screenshotTests` on a Nexus 
5 5.1.0 emulator and commit all screenshots that have changed.
* Assign gpeal as a reviewer.

LottieDrawable: {play/reverse}Animation: Assert progress and update setSetTime properly

---

LottieSample/build.gradle
LottieSample/src/main/java/com/airbnb/lottie/samples/AnimationFragment.java
LottieSample/src/main/res/layout/fragment_animation.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
lottie/build.gradle
lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Also show people the ideal scale as well as a slider to change it
in AnimationFragment.
Fixes #240

Expose setScale on LottieAnimationView and LottieDrawable

---

README.md

The example now illustrates how the color can be changed without having to implement a ColorFilter (which is non trivial as native code is involved)

Use PorterDuffColorFilter in example in README

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/res/values/attrs.xml

Set scale through xml.
Keep previously set scale.

Set scale.

---

lottie/src/main/java/com/airbnb/lottie/AnimatableTransform.java
lottie/src/main/java/com/airbnb/lottie/CircleShape.java
lottie/src/main/java/com/airbnb/lottie/ContentGroup.java
lottie/src/main/java/com/airbnb/lottie/ContentModel.java
lottie/src/main/java/com/airbnb/lottie/GradientFill.java
lottie/src/main/java/com/airbnb/lottie/GradientStroke.java
lottie/src/main/java/com/airbnb/lottie/Layer.java
lottie/src/main/java/com/airbnb/lottie/MergePaths.java
lottie/src/main/java/com/airbnb/lottie/PolystarShape.java
lottie/src/main/java/com/airbnb/lottie/RectangleShape.java
lottie/src/main/java/com/airbnb/lottie/ShapeFill.java
lottie/src/main/java/com/airbnb/lottie/ShapeGroup.java
lottie/src/main/java/com/airbnb/lottie/ShapePath.java
lottie/src/main/java/com/airbnb/lottie/ShapeStroke.java
lottie/src/main/java/com/airbnb/lottie/ShapeTrimPath.java

This removes the needs for Object type generics and instanceof checks

Added a ContentModel interface

---

lottie/src/main/java/com/airbnb/lottie/TextLayer.java

Fix small typeface error when drawing texts

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Potentially unsafe WeakReference handling
cc @gpeal

Make ref strong before checking it

---

LottieSample/src/main/kotlin/com/airbnb/lottie/samples/AnimationFragment.kt
LottieSample/src/main/kotlin/com/airbnb/lottie/samples/LottieFontViewGroup.kt
LottieSample/src/main/kotlin/com/airbnb/lottie/samples/TrimView.kt
LottieSample/src/main/res/drawable/ic_trim.xml
LottieSample/src/main/res/layout/fragment_animation.xml
lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/java/com/airbnb/lottie/LottieValueAnimator.java

Added support for setting the start/end frame/progress manually

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/res/values/attrs.xml

Nothing fancy in here… cf commits for more info

Various cleans

---

lottie/src/main/java/com/airbnb/lottie/LottieImageAsset.java

Useful with custom image asset delegate

Expose image relative directory name

---

lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/FillContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java
lottie/src/main/java/com/airbnb/lottie/utils/MiscUtils.java

Clamp alpha between 0 and 255

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

This mirrors some of ValueAnimator methods and might come in handy when using anonymous classes as listeners.

Methods for removing all of animator listeners

---

LottieSample/src/androidTest/java/com/airbnb/lottie/LottieSnapshotProvider.java
LottieSample/src/main/kotlin/com/airbnb/lottie/samples/AnimationFragment.kt
lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ColorKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/FloatKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/IntegerKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/PointKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ScaleKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ValueCallbackKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/value/LottieRelativeFloatValueCallback.java
lottie/src/main/java/com/airbnb/lottie/value/LottieRelativeIntegerValueCallback.java
lottie/src/main/java/com/airbnb/lottie/value/LottieRelativePointValueCallback.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticRelativeFloatValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticRelativeIntegerValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticRelativePointValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieValueCallback.java

This makes it easier to use it as a declarative API.

Added a setValue api to LottieValue

---

LottieSample/src/androidTest/java/com/airbnb/lottie/LottieSnapshotProvider.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticInterpolatedFloatValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticInterpolatedIntegerValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticInterpolatedPointValue.java
lottie/src/main/java/com/airbnb/lottie/value/LottieStaticInterpolatedValue.java

Added an interpolated lottie value

---

lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java

This is not always correct but can be very close and is at least
better than doing nothing.
Lottie will also log when this happens.
Fixes #601

Treat intersect masks like add masks

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Fix setProgress when startFrame > 0.

---

lottie/src/main/java/com/airbnb/lottie/model/KeyPath.java

...as Arrays.asLists already creates a List.

Removed unnecessary ArrayList wrapping

---

LottieSample/build.gradle

Before opening a pull request:
* If you added a new feature or fixed a bug, add a json file to assets/Tests and add a test 
for it in `LottieTest#testAll`.
* Run screenshot tests by running `./gradlew --daemon recordMode screenshotTests` on a Nexus 
5 5.1.0 emulator and commit all screenshots that have changed.
* Assign gpeal as a reviewer.

[Sample App] Change annotation processor of butterknife lib

---

LottieSample/src/androidTest/java/com/airbnb/lottie/LottieSnapshotProvider.java
lottie/src/main/java/com/airbnb/lottie/value/LottieValueCallback.java

This prevented you from clearing a ColorFilter
Fixes #638

Remove null restriction on value callbacks

---

lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java

setMinFrameSmallerThanComposition should set minFrame, not maxFrame.

Fix small test issue.

---

LottieSample/src/androidTest/java/com/airbnb/lottie/LottieSnapshotProvider.java
lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/FillContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/StrokeContent.java

ColorFilter animations were not properly registered as animations so they wouldn't update the animation when changed.
Fixes #690

Properly register ColorFilter animations

---

LottieSample/src/androidTest/java/com/airbnb/lottie/LottieSnapshotProvider.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java
lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java

The order of parameters was flipped for `lerp`.
Added tests and did an audit of all other lerp calls to make sure they were all fine.
Fixes #739

Fixed min/max progress

---

README.md

Before opening a pull request:
* If you added a new feature or fixed a bug, add a json file to assets/Tests and add a test 
for it in `LottieTest#testAll`.
* Run screenshot tests by running `./gradlew --daemon recordMode screenshotTests` on a Nexus 
5 5.1.0 emulator and commit all screenshots that have changed.
* Assign gpeal as a reviewer.

change compile to implementation

---

README.md

2.5.5 has been out already for a few weeks

Update latest version in README.md

---

lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
lottie/src/main/java/com/airbnb/lottie/parser/MaskParser.java

Add an intersect mask warning at parse time

---

lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java

Gracefully degrade when null bitmaps are set

---

lottie/src/main/java/com/airbnb/lottie/LottieTask.java

Make EXECUTOR non-final

---

lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java

@bmc08gt 
Reverts airbnb/lottie-android#919

Revert "CompositionLayer: Handle invalid Region.Op on Android Pie"

---

lottie/src/main/java/com/airbnb/lottie/LottieTask.java

Synchronize task threading

---

lottie/src/main/java/com/airbnb/lottie/model/DocumentData.java
lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java
lottie/src/main/java/com/airbnb/lottie/parser/DocumentDataParser.java

Make text strokeWidth a double

---

lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ColorKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/FloatKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/IntegerKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/PathKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/PointKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/ScaleKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/value/LottieValueCallback.java

Allow returning null from value animator callbacks

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/res/values/attrs.xml

Added an attr for speed

---

lottie/src/main/java/com/airbnb/lottie/parser/GradientFillParser.java

Add a default gradient fill type

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Clean up docs and add documentation link to LottieDrawable and LottieAnimationView

---

lottie/src/main/java/com/airbnb/lottie/animation/LPaint.java
lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/FillContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/model/content/ShapeData.java
lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
lottie/src/main/java/com/airbnb/lottie/model/layer/ImageLayer.java
lottie/src/main/java/com/airbnb/lottie/model/layer/SolidLayer.java
lottie/src/main/java/com/airbnb/lottie/utils/Utils.java

Paint's constructor calls `setTextLocales` which takes ~1ms. We don't need it for most Lottie drawing so we can just noop it to save the time.

Created LPaint optimization

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Optimize invalidateSelf

---

lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java

Properly check values have changed before notifying listeners.

Flipped equality check

---

lottie/src/main/java/com/airbnb/lottie/model/content/ShapeData.java

Be more lenient with shapes that have a different number of control points

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
lottie/src/main/java/com/airbnb/lottie/model/LottieCompositionCache.java
lottie/src/test/java/com/airbnb/lottie/LottieCompositionFactoryTest.java

I also added an API to set the max cache size and tests.
Fixes #1077

Properly limit LRU cache size and make it configurable

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Other streams are closed so this makes it consistent with that.
Fixes #1068

Close JsonReader after parsing

---

lottie/src/main/java/com/airbnb/lottie/LottieTask.java

I noticed that the observer thread approach that was being used to check when LottieTasks are done has indeterminate delay for reporting finished tasks, since the thread polls the task. It also adds overhead to create a thread for each task.
Digging into it, it looks like we can simply use FutureTask's `done` function to know when the task is done.
With this change the sample app seems to run perfectly, so functionality seems to be the same.

Replace task observer thread with FutureTask subclass

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java

Also cleaned up some stuff from the original masks PR.

Added support for inverted intersect masks

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Prevent a crash on older versions of Android

---

LottieSample/src/androidTest/java/com/airbnb/lottie/LottieTest.kt
lottie/src/main/java/com/airbnb/lottie/LottieProperty.java
lottie/src/main/java/com/airbnb/lottie/animation/content/RectangleContent.java

I'll fix formatting in next push

radius, size & position value callbacks for rectangle

---

lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java

This is to fix #1214 . Please check out the root cause analysis in #1214 .

 Refer to the frameTimeNanos from Choreographer (#1214)

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Set wasAnimatingWhenDetached to false at pause()

---

lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java

@dloic, #1162 broke all url loading because you closed the connection before it was actually done being used. This fixes it though.
Fixes #1219

Close url connection at the right time

---

lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java

Set correct frame when animation ends and speed is < 0

---

lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java

Default null content type to JSON

---

lottie/src/main/java/com/airbnb/lottie/PerformanceTracker.java

Fix removing frame listeners in PerformanceTracker

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Somehow this was never implemented when adding the renderMode API
#1254

Fixed renderMode attr

---

lottie/src/main/java/com/airbnb/lottie/animation/content/BaseStrokeContent.java

Thanks @karip for the animation and fix.
Fixes #798

Apply scale to dash pattern offset

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/parser/moshi/package-info.java

This PR also hides the visibility of the Lottie Moshi JSON parsing classes.
Fixes #1270

Replace LottieAnimiationView JsonReader API with just InputStream

---

lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java

Fuzzy match content types

---

LottieSample/src/main/res/layout/control_bar.xml
lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java

Clear mask canvases on pre-Pie

---

lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java
lottie/src/main/java/com/airbnb/lottie/animation/content/GradientStrokeContent.java

Fixes the second half of #1188
@Moes81

Apply parent matrix to gradient stroke

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Prevent a StackOverflowException on 4.4

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Prevent removeAllUdpateListeners from breaking all future animations

---

build.gradle
lottie/build.gradle
lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

It won't do much right now as most errors are off but they can now be turned on and fixed one by one.
Fixes #1330

Add Nullaway support

---

lottie/src/main/java/com/airbnb/lottie/utils/Utils.java

using 'matrix approach' to resize the bitmap

resizing bitmap function as per issue #1380

---

lottie/build.gradle

Make it easy for user to build sourceJar file at local environment.

Add sourceJar task.

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java

- render the very last frame in resumeAnimation as playAnimation.
- call animation end in case app listens to the callback.

Improve testability when systemAnimation is disabled.

---

LottieSample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt
lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Support ScaleType.FIT_XY in LottieDrawable. 
Use the same way used in draw() method to do extra scale.

Support ScaleType.FIT_XY in Lottie.

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Prevent a NPE when creating LottieAnimationView

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Fix https://github.com/airbnb/lottie-android/issues/1432.

Fix NPE when set ScaleType in xml.

---

lottie/src/main/java/com/airbnb/lottie/utils/Utils.java

> figure out why the result needs to be divided by 2
the length of hypotenuse of isosceles right triangle that legs are sqrt(2) is 2. to get the length 1, legs are 1/sqrt(2).

solved TODO of Utils.getScale()

---

LottieSample/src/androidTest/java/com/airbnb/lottie/samples/FragmentVisibilityTests.kt
lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Test failed before but passes now
Fixes #1428 
cc @CodeRedDev

Save play state in SavedState even if view was detached from the window first

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/java/com/airbnb/lottie/LottieLogger.java
lottie/src/main/java/com/airbnb/lottie/utils/LogcatLogger.java
lottie/src/main/java/com/airbnb/lottie/utils/Logger.java

This allows you to wrap draw with a try/catch for specific problematic devices. Please read its doc before using.
#1422

Add a safeMode API

---

LottieSample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt
lottie/src/main/java/com/airbnb/lottie/LottieProperty.java
lottie/src/main/java/com/airbnb/lottie/model/DocumentData.java
lottie/src/main/java/com/airbnb/lottie/model/layer/TextLayer.java
lottie/src/main/java/com/airbnb/lottie/parser/DocumentDataParser.java

Also made DocumentData float values to be more consistent with the rest of the codebase.
Fixes #1421

Added a dynamic property for text size

---

lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java

Fixes https://github.com/airbnb/lottie-android/issues/1498

Always notify update when a composition is set

---

lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java

Fixes https://github.com/airbnb/lottie-android/issues/1489

Properly clear canvas for masks pre-Pie

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Fixes https://github.com/airbnb/lottie-android/issues/1517

Play, not resume, animation when playAnimation() is called when isShown() is false

---

LottieSample/src/main/kotlin/com/airbnb/lottie/samples/LottiefilesFragment.kt

Fix https://github.com/airbnb/lottie-android/issues/1580
Ref: https://github.com/android/architecture-components-samples/blob/7f861fd45d158e6277a3c35163c7f663e135b2cf/PagingWithNetworkSample/app/src/main/java/com/android/example/paging/pagingwithnetwork/reddit/repository/inMemory/byPage/PageKeyedSubredditDataSource.kt#L110

Fix crash of sample #1580

---

build.gradle
lottie/src/main/java/com/airbnb/lottie/model/layer/Layer.java
lottie/src/main/java/com/airbnb/lottie/parser/LayerParser.java

Fixes https://github.com/airbnb/lottie-android/issues/1633

Added warnings for unsupported matte types

---

lottie/src/main/java/com/airbnb/lottie/animation/content/GradientFillContent.java

See https://github.com/airbnb/lottie-android/issues/1608

Clear hashed gradient objects when a new value callback is set.

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Cache compositions loaded by url in memory

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Resolves #1644 by adding methods to LottieAnimationView and LottieDrawable

Add Animator.AnimatorPauseListener support

---

lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimationState.kt
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
sample-compose/build.gradle
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/ComposeActivity.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/Route.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/composables/AnimationRow.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/lottiefiles/LottieFilesSearchPage.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/PlayerPage.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/preview/PreviewPage.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/ui/Color.kt
sample-compose/src/main/res/drawable/ic_layers.xml
sample-compose/src/main/res/drawable/ic_masks_and_mattes.xml
sample-compose/src/main/res/drawable/ic_warning.xml
sample-compose/src/main/res/values/strings.xml

Added apply opacity to layers, outline masks and mattes, and enabled merge paths by default. Also fixed some bugs in the sample app and added the ability load a file from a url.

[Compose] Added more functionality to the player and sample

---

lottie/src/main/java/com/airbnb/lottie/LottieImageAsset.java
sample/src/main/kotlin/com/airbnb/lottie/samples/PlayerFragment.kt
sample/src/main/kotlin/com/airbnb/lottie/samples/model/CompositionArgs.kt
sample/src/main/res/layout/bullseye_activity.xml

Fixed a few bugs in the sample app

---

lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimationState.kt

Some cleanup from a code review with Leland Richardson

[Compose] Cleanup

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

https://github.com/airbnb/lottie-android/issues/1585

Add more info to setMaxFrame docs

---

lottie/src/main/java/com/airbnb/lottie/animation/content/ContentGroup.java
lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
sample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt

Fixes https://github.com/airbnb/lottie-android/issues/974

Allow targeting mattes with KeyPaths

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Ignore unscheduleDrawable when updating a composition

---

build.gradle
sample-compose/build.gradle
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/ComposeActivity.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/composables/AnimationRow.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/composables/Loader.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/lottiefiles/LottieFilesPage.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/PlayerPage.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/player/ToolbarChip.kt
sample-compose/src/main/java/com/airbnb/lottie/sample/compose/preview/PreviewPage.kt

[Compose] Update to Beta 01

---

CHANGELOG_COMPOSE.md
build.gradle
sample-compose/build.gradle

Update to Compose Beta 02

---

.gitignore
.idea/inspectionProfiles/Project_Default.xml
lottie/src/main/java/com/airbnb/lottie/parser/GradientColorParser.java

Prevent duplicate positions in gradient fills

---

build.gradle

Really tiny change! Gave it a quick test run and all looks good 🙌

Update to Compose Beta 03

---

build.gradle

This will fix our Robolectric tests, yay!

Update to AGP 7.0.0-Alpha12

---

lottie/src/main/java/com/airbnb/lottie/TextDelegate.java
sample/src/androidTest/java/com/airbnb/lottie/samples/FragmentVisibilityTests.kt
sample/src/androidTest/java/com/airbnb/lottie/samples/LottieTest.kt

Made TextDelegate.getText public and updates its docs

---

LICENSE

This reverts commit 7b5e052ca3964dccad1aabe7c147f9191122aa0f.
Part of https://github.com/airbnb/lottie-android/issues/527

Revert "Fix copyright ownership"

---

lottie/src/main/java/com/airbnb/lottie/L.java

Fixes https://github.com/airbnb/lottie-android/issues/1798

Use app context in NetworkFetcher

---

build.gradle
issue-repro-compose/build.gradle
lottie-compose/build.gradle
sample-compose/build.gradle
sample/build.gradle
sample/src/main/kotlin/com/airbnb/lottie/samples/MainActivity.kt
sample/src/main/kotlin/com/airbnb/lottie/samples/ShowcaseFragment.kt
sample/src/main/kotlin/com/airbnb/lottie/samples/model/AnimationDataV2.kt
sample/src/main/kotlin/com/airbnb/lottie/samples/model/AnimationResponseV2.kt

Had to fix a Lottiefiles model because it was NPEing calculating the hash code on a field that wan't being used anyway.

Upgrade Compose to rc01 plus other dependencies

---

CHANGELOG.md

Fixed version in CHANGELOG

---

lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java

Fix blur scale

---

.github/workflows/validate.yml

See [Disable publish action in forked repository](https://github.com/square/kotlinpoet/pull/1119).

Disable deploy action in forked repository

---

deploy_snapshot.sh

Fix publish credentials

---

lottie/src/main/java/com/airbnb/lottie/animation/content/ShapeContent.java
lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java

Fixes #1632 
Fixes #1879 
Fixes #1815

Prevent two rare crashes

---

lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java

Add x-zip and x-zip-compressed as recognized .zip header mime types

---

lottie/src/main/java/com/airbnb/lottie/animation/keyframe/TransformKeyframeAnimation.java

Fix a rare NPE race condition in TransformKeyframeAnimation

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Fix Android Studio layout preview

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Fixes https://github.com/airbnb/lottie-android/issues/1841

Prevent LottieAnimationView from overwriting user actions when restoring from saved instance state

---

lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java

Fix a Xiaomi specific crash

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java

Remove rounding from setMaxFrame

---

sample-compose/src/androidTest/java/com/airbnb/lottie/samples/WalkthroughAnimationTest.kt

Fix WalkthroughAnimationTest

---

lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java

Only store application context in ImageAssetManager

---

lottie/src/main/java/com/airbnb/lottie/animation/content/ContentGroup.java
lottie/src/main/java/com/airbnb/lottie/animation/content/RepeaterContent.java
snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/DynamicPropertiesTestCase.kt

Allow repeater contents to have dynamic properties

---

.gitignore
lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
lottie/src/main/java/com/airbnb/lottie/LottieTaskIdleListener.java
sample/src/androidTest/java/com/airbnb/lottie/samples/FragmentVisibilityTests.kt
sample/src/androidTest/java/com/airbnb/lottie/samples/LottieIdlingResource.kt

Enable configuring a global idling resource

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/res/values/attrs.xml

Allow setting a default font file extension

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java
lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java

Allow ImageAssetDelegate to be used with a LottieDrawable that doesn't have a callback

---

.github/workflows/validate.yml
snapshot-tests/build.gradle

These should be much faster than the existing firebase cloud test lab snapshots.

Run snapshot tests on emulator.wtf

---

.github/workflows/validate.yml
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/TransformKeyframeAnimation.java

Not sure why this is happening but it seems similar to #1955.
Fixes https://github.com/airbnb/lottie-android/issues/2194

Add an extra null check for transform anchorPosition

---

lottie/src/main/java/com/airbnb/lottie/network/NetworkFetcher.java

Use the correct cache key when parsing NetworkFetcher animations

---

.github/workflows/validate.yml

This should allow secrets to be used in PRs

Change PR workflow to pull_request_target

---

lottie/src/main/java/com/airbnb/lottie/utils/BaseLottieAnimator.java
lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java
lottie/src/test/java/com/airbnb/lottie/utils/LottieValueAnimatorTest.java

LottieValueAnimator doesn't utilize a base implementation of pause and resume methods of Animator.
The result is undispatched events to AnimatorPauseListener.

Fix AnimatorPauseListener callbacks

---

lottie/src/main/java/com/airbnb/lottie/L.java
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
lottie/src/main/java/com/airbnb/lottie/model/layer/BaseLayer.java
lottie/src/main/java/com/airbnb/lottie/model/layer/CompositionLayer.java
lottie/src/main/java/com/airbnb/lottie/utils/LottieTrace.java

This improves the traceability of some new multi-threaded performance investigations I am working on.

Added more systrace markers and made LottieTrace multi-thread compatible

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Remove restriction that zip files must provide all images

---

.idea/codeStyles/Project.xml
sample/src/main/res/layout/control_bar_player_controls.xml

I think Android studio stupidly moved it when reformatting the XML file
https://github.com/airbnb/lottie-android/pull/2285/files?w=1#diff-88c2db4357feeb499e5575ffff22a6033726360396731ebee771870b2f5a88f1L73

[Sample app] Fix loop button position

---

gradle.properties
lottie/src/main/java/com/airbnb/lottie/network/NetworkCache.java

Fixes https://github.com/airbnb/lottie-android/issues/2309

Allow loading URLs that are more than 255 chars

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Add close parameters to LottieCompositionFactory.fromZipStream

---

lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt
lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt

Add @JvmOverloads to LottieAnimatable

---

.github/workflows/validate.yml

https://blog.emulator.wtf/posts/2023-07-04-gpu-emulators/

Enable GPU for emulator.wtf

---

lottie/src/main/java/com/airbnb/lottie/animation/keyframe/TransformKeyframeAnimation.java

Fixes https://github.com/airbnb/lottie-android/issues/2354

Add an additional null check to TransformKeyframeAnimation

---

lottie/src/main/java/com/airbnb/lottie/LottieDrawable.java

Fixes https://github.com/airbnb/lottie-android/issues/2355

Fix asyncUpdates for Nougat and below

---

versions.properties

Upgrade okio to 1.17.6

---

lottie/src/main/java/com/airbnb/lottie/model/layer/SolidLayer.java
snapshot-tests/src/androidTest/java/com/airbnb/lottie/snapshots/tests/DynamicPropertiesTestCase.kt

Fixes https://github.com/airbnb/lottie-android/issues/2422

Handle null color callbacks in SolidLayer

---

lottie-compose/src/test/java/com/airbnb/lottie/compose/LottieClipSpecTest.kt
lottie/src/main/java/com/airbnb/lottie/LottieComposition.java
lottie/src/main/java/com/airbnb/lottie/LottieImageAsset.java
lottie/src/main/java/com/airbnb/lottie/parser/LottieCompositionMoshiParser.java
lottie/src/test/java/com/airbnb/lottie/LottieDrawableTest.java
lottie/src/test/java/com/airbnb/lottie/LottieValueAnimatorUnitTest.java

Fixes https://github.com/airbnb/lottie-android/issues/2216

Scale image if the dp scale changes

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java
lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java
lottie/src/main/java/com/airbnb/lottie/LottieTask.java

Fixes https://github.com/airbnb/lottie-android/issues/2326

Make all LottieAnimationView setters idempotent

---

lottie/src/main/java/com/airbnb/lottie/animation/keyframe/PathKeyframeAnimation.java

As discussed in https://github.com/airbnb/lottie-android/pull/2457

Better tangent extrapolation implementation when using bounce easings

---

lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java

Fixes https://github.com/airbnb/lottie-android/issues/2467

Remove LottieAnimationView.composition so it doesn't get out of sync

---

.idea/kotlinc.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties
lottie/src/main/java/com/airbnb/lottie/animation/keyframe/BaseKeyframeAnimation.java
settings.gradle
versions.properties

Fixes https://github.com/airbnb/lottie-android/issues/2471

Upgrade a bunch of dependencies

---

lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimation.kt

Fixes https://github.com/airbnb/lottie-android/issues/2446

Clarify clipToCompositionBounds docs for Compose

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

fromJsonInputStreamSync() would just convert the InputStream back into a Source.

LottieCompositionFactory: Reduce Source -> InputStream -> Source conversion.

---

lottie/src/main/java/com/airbnb/lottie/manager/ImageAssetManager.java

Fix an NPE here which regressed from https://github.com/airbnb/lottie-android/pull/2289/files

Fix NPE in ImageAssetManager#hasSameContext (#2503)

---

.github/workflows/validate.yml

https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

[CI] Update actions/upload-artifact

---

lottie-compose/src/main/java/com/airbnb/lottie/compose/rememberLottieComposition.kt
lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Unify the parsing of generic input streams

---

lottie/src/main/java/com/airbnb/lottie/LottieCompositionFactory.java

Add an option to not clear the network cache

---

RELEASE.md

I really enjoyed using this project, nice work! Caught a couple of typos in the README though 😛

Update RELEASE.md, fix a typo

---

lottie/src/main/java/com/airbnb/lottie/utils/LottieValueAnimator.java

I encount blinking issue with a company internal resource.
Problem reproduction steps：
1. setMinAndMaxFrame(m, n) and repeatCount = INFINITE
2. it will notifyUpdate when animation ended, but the frame has not been reset to minFrame at this time. 
2. so it will draw n+1 frame.

Fix blinking issue when loop the animation in minFrame and maxFrame

---

lottie/src/main/java/com/airbnb/lottie/parser/LottieCompositionMoshiParser.java

Parse as width/height as double

---

lottie-compose/src/main/java/com/airbnb/lottie/compose/LottieAnimatable.kt

Better handle clip specs when minProgress == maxProgress

---

lottie/src/main/java/com/airbnb/lottie/LottieTask.java
lottie/src/test/java/com/airbnb/lottie/LottieInitializeTest.java
lottie/src/test/java/com/airbnb/lottie/LottieTaskTest.java

Closes #2612 
2 minutes to fix behavior. 2 hours to get test working.

Support system property to set a testing executor
